var GAME_LEVELS = [

   ["  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x           oo                      oooooooooooo                           x  ",
    "  x           xx                     xxxxxxxxxxxxxx                          x  ",
    "  x  @       xxxx       ###         xxxxxxxxxxxxxxxx      ###    ooooo       x  ",
    "  x         xxxxxx                 xxxxxxxxxxxxxxxxxx            xxxxx       x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxyyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                "],


   ["                                                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xx",
    "                                                                              xx                                       xx",
    "                                                                              xx                       o               xx",
    "                                                                              xx                                  xx   xx",
    "                                                                              xx                           xxxxxxxxx   xx",
    "                                                                              xx              ###               xxxx o xx",
    "                                                                              xx           xxxxxxxxxxxx         xxxx   xx",
    "                                                                              xx                                xxxx o xx",
    "                                                                              xx              ###             xxxxxx   xx",
    "                                                                                                                xxxx o xx",
    "                                                                                           xxxxxxxxxxxxx        xxxx   xx",
    "                                                                                                                xxxx o xx",
    "                                                                                                             xxxxxxx   xx",
    "                                                                                                                xxxx o xx",
    "                                                                                                        o       xxxx   xx",
    "                                                                                                                xxxx o xx",
    "                                                                                         ###                xxxxxxxx   xx",
    "                                                                                                                xxxx o xx",
    "                                                                 ###               xxyyxxxxxxxxxxxxxxx          xxxx   xx",
    "     @         #      #                                                  xxyxxxxxxxxxxxxxxxxxxx     xx          xxxx o xx",
    "                                                                 xxxxyxxxxxxxxxxxxxxxxxx     v      xx          xxxx   xx",
    "    xxx                                                   xxyxxxxxxxxxxxxxxxxxx                     xx          xxxx o xx",
    "    xxx    xyx    xyx    xyx                                 xx           xx                        xx          xxxx   xx",
    "!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx",
    "!!!!xxx!!!!!!!!!!!!!!!!!!!!!!xx   o   xxxxxxxxxx     x!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx",
    "!!!!xxx!!!!!!!!!!!!!!!!!!!!!!x    o                 xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx",
    "!!!!xxx!!!!!!!!!!!!!!!!!!!!!!x    o    oooooooo    xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx",
    "!!!!xxx!!!!!!!!!!!!!!!!!!!!!!xx   o   xxxxxxxxxxxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx",
    "!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx"],


  ["!      !          v       v                  v                   v                 v                          ",
   "!  @   !                                                                                                      ",
   "!      !                                                                                                      ",
   "!      !                                                                                                      ",
   "!      !                                                                                                      ",
   "!  #   !                                                                                                      ",
   "!      !                                                                                                      ",
   "!      !                                                                                                      ",
   "!      !                                                                                                      ",
   "!      !                                                                                                      ",
   "!  #   !                                                                                                      ",
   "!      !!                                                                                                     ",
   "!      !!!                                                                                                    ",
   "!      !!!!                   |                                                                           o   ",
   "!      !!!!!                                 o                                                                ",
   "!      !!!!!!                                         #                                                  #    ",
   "!      !!!!!!!                                                                                                ",
   "!      !!!!!!!!                               yxxx                                             o        xxxy  ",
   "!  #   !!!!!!!!!         |                       v            #                                               ",
   "!      !!!!!!!!!!                                    xxxx                               o        xxxx         ",
   "!      !!!!!!!!!!!                                     v                                            v         ",
   "!      !!!!!!!!!!!!!!!!                                      xyxx                         xxyx                ",
   "!  #   !!!!!!!!!!!!!!!!!!!!                 |                                o                                ",
   "!      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                      xxxx           xxxx                       ",
   "!      xxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxx                                                                ",
   "!                                                                           xxxx                              ",
   "!               o        o      #      o     #                       xxxx                                     ",
   "!                                                            xyxx                                             ",
   "!                                                    xxxx                                                     ",
   "!xyyxxxxxxxxxx     xxxx     xxxxxxxxx     xxxxxxx                                                     |       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x              x   x               x         x   !                         x  ",
    "  x              x   x               x         x                             x  ",
    "  x         xx    xxx   xx   x  x    x    x    x   x  xxxx                   x  ",
    "  x  @             x   x  x  x  x     x  x x  x    x  x  x                   x  ",
    "  x                x    xx   xxxx      xx   xx     x  x  x                   x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyxxxxx  ",
    "                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
